version: "2.20"

services:
  app:
    container_name: food-network-app
    image: docker.io/library/the-food-network-image:latest
    working_dir: /foodnetwork
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm start
      
